### ISSUE TITLE
Closing menu in a sticky header scrolls up the page (Chrome only)

### ISSUE THREAD

**Issue by rslawik** [PolymerElements/paper-dropdown-menu#261]
### Description

Dropdown menu inside a sticky header after closing scrolls up the page.

```css
header.sticky {
  position: -webkit-sticky;
  position: sticky;
  top: 0;
}
```

### Expected outcome

Closing menu doesn't change the scroll position of the page.

### Actual outcome

Page is scrolled up.

### Live Demo

http://jsbin.com/vocemoyato/1/edit?html,css,output

### Steps to reproduce

1. Put `<paper-dropdown-menu>` in a sticky header.
2. Scroll the page down (so the header is stuck at the top).
3. Open the menu.
4. Select (or close).

### Browsers Affected

- [x] Chrome 61
- [ ] Chrome Canary (63)
- [ ] Firefox
- [ ] Safari 10
