### ISSUE TITLE
paper-dropdown-menu not working in the drawer of a paper-drawer-panel

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-dropdown-menu#27]
The `paper-dropdown-menu` doesn't work properly when it's inside the `drawer` of a `paper-drawer-panel` in `narrow layout` state, the `paper-menu` dropdown will not open. It works normally when the `paper-drawer-panel` is not in the `narrow` state

**Comment by kungufli** [comment]
After further investigation it seems that it could be a problem related to the `z-index`, since the menu actually opens but is not visible if the `drawer` is in `narrow` state, and become visible if the page is expanded so the `drawer` is not `narrow` anymore:

![dropdown](https://cloud.githubusercontent.com/assets/12832388/9636661/ebe6c1aa-519c-11e5-8c9b-8f3f58165706.gif)

**Comment by softkot** [comment]
It seems to be the same reason why it is not shown inside paper dialogs.

**Comment by tigerhawkvok** [comment]
Hit this too. Potential (ugly) workaround:


```css
paper-dropdown-menu, paper-menu, .force-adj-paper-menu {
    z-index:9998!important;
}
iron-dropdown.paper-menu-button {
    z-index:9999!important;
    right: inherit!important;
    left: inherit!important;
    top: inherit!important;
}
```
